### ISSUE TITLE
BZ report says latest rawhide build is the EPEL7 one

### ISSUE THREAD

**Issue by scop** [fedora-infra/the-new-hotness#98]
https://bugzilla.redhat.com/show_bug.cgi?id=1303383

> Latest upstream release: 2.5.2
> Current version/release in rawhide: 2.0-5.el7

That is not the latest rawhide build, it's the latest EPEL7 one (from over a year ago). Current rawhide one is 2.5.1-1.fc24.

**Comment by thmo** [comment]
I have a similar problem with python-regexp, see https://bugzilla.redhat.com/show_bug.cgi?id=1303383: The version in rawhide is 2016.04.25-1.fc25, yet the-new-hotness thinks it would be 2015.07.19-1.el7.

@ralphbean found out the reason while we chatted in #fedora-apps.

python-regex (the source rpm) builds a python2-regex and a python3-regex subpackage, but no python-regex rpm. The-new-hotness searches for python-regex though, in https://kojipkgs.fedoraproject.org/repos/rawhide/latest/, fails to find it and then falls back to what it finds on the el7 box it runs on.

So, the bug here is that it looks in the arch/noarch _result_ repositories, while it should probably look into the _source_ repository, and another bug is that it shouldn't fall back to some random, locally configured repository.

**Comment by thmo** [comment]
And searching a bit more through the issues, this is basically a duplicate of the more general #84.

**Comment by ignatenkobrain** [comment]
https://github.com/fedora-infra/the-new-hotness/commit/2eed58c4ea09729f17e8c672196318d7028b0dba

**Comment by jeremycline** [comment]
Closing as fixed in #128

**Comment by scop** [comment]
@jeremycline is this fix already in production? Asking because just yesterday a bug was filed that still shows the old buggy behavior: https://bugzilla.redhat.com/show_bug.cgi?id=1394988

**Comment by jeremycline** [comment]
@scop no, it's just been merged into the development branch. My hope was to sort through all the issues this week, come up with a changelog, get the one outstanding PR merged, and then make a release.
